### ISSUE TITLE
GPU - out of memory errors

### ISSUE THREAD

**Issue by dardanbekteshi** [yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks#5]
I have noticed that when the model is training, Caffe keeps the whole training set in memory, even though the batch size is set to 1! After that, when testing starts, Caffe doesn't release the training set, but just adds the whole test set in memory again. This makes it very hard to train/test on bigger datasets, since everything is kept in GPU memory. I have an NVIDIA GPU with 4GB of VRAM, and the biggest dataset I can train on is 30 meshes (average of 10.000 triangles per mesh). 

I am wondering, have you experienced anything similar and do you know how can I make Caffe to only keep in memory one batch at a time, and not the whole training set?

ping @yuangan

**Comment by yuangan** [comment]
I asked my partner, he said, that's mainly because of LMDB. You could create a python layer to read data.

**Comment by dardanbekteshi** [comment]
Thanks for the quick answer! That seems to be true, based on this comment: https://github.com/BVLC/caffe/issues/2121#issuecomment-82995998

I'll probably try LevelDB instead.

**Comment by yuangan** [comment]
Good Luck! We run the code in Titan X, so there is no such problem :)
