### ISSUE TITLE
graph cut part example.

### ISSUE THREAD

**Issue by panganqi** [yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks#6]
How to run the GCO part? I've seen the test folder and the Desktop folder but don't know how to use them

**Comment by yuangan** [comment]
Sorry, I'm a little busy recently. Two days later, I'll upload our example code.

**Comment by yuangan** [comment]
I've uploaded the example code of our graph cut. If you just want to know how to use GCO, you can refer to example.cpp in gco. That's their official example.
