### ISSUE TITLE
Cannot export extra features like dist, area, adj, seg

### ISSUE THREAD

**Issue by peihaowang** [yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks#7]
Sorry for this probably stupid question. But after I run the code under `segmesh`, I can only find features saved in files with suffix of `.off.txt`, like those saved in `plier_fea`. But I suppose your code requires more features, like dist, area, adj, seg saved in `plier_all`. Where can I find them? I noticed the code differs a little bit from Kalogerakis', but I didn't get deeper into the details. I run the code provided by both you and Kalogerakis, unfortunately neither exports the missing features mentioned before. The README.md states that all of those features are just generated by Kalogerakis' code, but I still believe some are missing since I've checked the code several times.

Any reply would be appreciated. Thank you.

**Comment by yuangan** [comment]
Hi, I think we calculate the dist, area, adj and so on by ourselves. I'm sorry we haven't made it clear. I think it's not difficult to implement with Kalogerakis's code. And there is an example of how to calculate them: https://github.com/yuangan/GraphCut 

Thank you for your attention.
